apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-weather
  name: app-weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-weather
  strategy: {}
  template:
    metadata:
      labels:
        app: app-weather
    spec:
      containers:
      - image: docker.io/nadermamdouh869/weather-app:latest 
        name: weather-app
