apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-svc
  name: app-svc
spec:
  type: LoadBalancer
  selector:
    app: app-weather
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
