name: Ci/Cd Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Job1:
    name: My k8s job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_K8S }}" | base64 --decode > $HOME/.kube/config
          cat $HOME/.kube/config

      - name: Use context
        run: |
          kubectl config use-context cicd-nader-context

      - name: Get Nodes
        run: kubectl get nodes